datasets:
  retinopathy_dataset:
    num_classes: 5
    root_path: '/home/co-dutt1/rds/hpc-work/MLP-RIQA/data/diabetic-retinopathy-detection/' #Root path to the images
    train_df_path: '/home/co-dutt1/rds/hpc-work/MLP-RIQA/Train_set_RIQA_DR_Labels.csv'  #Path to read the training dataset file
    test_df_path: '/home/co-dutt1/rds/hpc-work/MLP-RIQA/Test_set_RIQA_DR_Labels.csv' #Path to read the test dataset file

    train_cat_labels: ['Good', 'Usable', 'Reject']
    test_cat_labels: ['Good', 'Usable', 'Reject']
    val_cat_labels: ['Good', 'Usable', 'Reject']

  chexpert:
    root_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CheXpert_dataset/'
    train_df_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CheXpert_dataset/CheXpert-v1.0-small/train.csv'
    valid_df_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CheXpert_dataset/CheXpert-v1.0-small/valid.csv'

  cancer_mnist:
    num_classes: 7
    root_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CancerMNIST/'
    train_df_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CancerMNIST/HAM10000_metadata.csv'

  mura:
    root_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/MURA_dataset/MURA-v1.1/'

run:
  batch_size: 256
  model: 'dorsal'
  dataset: 'retinopathy'
  lr_rate: 0.1
  epochs: 50
  

