all_datasets:
  retinopathy:
    num_classes: 5
    root_path: '/home/co-dutt1/rds/hpc-work/MLP-RIQA/data/diabetic-retinopathy-detection/' #Root path to the images
    train_df_path: '/home/co-dutt1/rds/hpc-work/MLP-RIQA/Train_set_RIQA_DR_Labels.csv'  #Path to read the training dataset file
    test_df_path: '/home/co-dutt1/rds/hpc-work/MLP-RIQA/Test_set_RIQA_DR_Labels.csv' #Path to read the test dataset file

    train_cat_labels: ['Good', 'Usable', 'Reject']
    test_cat_labels: ['Good', 'Usable', 'Reject']
    val_cat_labels: ['Good', 'Usable', 'Reject']

  chexpert:
    num_classes: 14
    root_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CheXpert_dataset/'
    train_df_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CheXpert_dataset/CheXpert-v1.0-small/train_final.csv'
    val_df_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CheXpert_dataset/CheXpert-v1.0-small/valid_final.csv'

  cancer_mnist:
    num_classes: 7
    root_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CancerMNIST/'
    train_df_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CancerMNIST/HAM10000_modified_metadata.csv'

  mura:
    num_classes: 2
    root_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/MURA_dataset/'
    train_df_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/MURA_dataset/MURA-v1.1/train_paths_with_labels.csv'
    val_df_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/MURA_dataset/MURA-v1.1/valid_paths_with_labels.csv'


run:
  batch_size: 128
  lr_rate: 0.001
  epochs: 20
  subset: null
  auto_lr_find: True
  save_plots: True
  experiment: 'k_bit_embeddings'
  do_finetune: True

  

