model:
  encoder: 'resnet50_supervised'
training:
  batch_size: 10
  num_aug_samples: 10
  verbose: True
dataset:
  num_dummy_samples: 5
  use_dataset: 'diabetic_retinopathy'   #Name of the dataset to use. Options: ['diabetic_retinopathy', 'dummy', 'cancer_mnist', 'mura']
DR_DATASET:
  root_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/diabetic-retinopathy-detection/'
  train_df_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/diabetic-retinopathy-detection/Train_set_RIQA_DR_Labels.csv'
  test_df_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/diabetic-retinopathy-detection/Test_set_RIQA_DR_Labels.csv'
CHEX_DATASET:
  root_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CheXpert_dataset/'
  train_df_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CheXpert_dataset/CheXpert-v1.0-small/train.csv'
  valid_df_path: '/home/co-dutt1/rds/hpc-work/SSL-Augmentations/data/CheXpert_dataset/CheXpert-v1.0-small/valid.csv'
  